name: Updater CI

on: workflow_dispatch

jobs:
  release-update:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'Antiwall')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Release updater file
        run: npm run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
